name: prettier

on:
  push:
    branches:
      - docs
    paths: 外部設計/API定義/OpenAPI.yml
    workflow_dispatch: # 手動実行用の設定項目
  pull_request: ~

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install prettier
        run: npm ci

      - name: Check formatting
        run: npm run check
