name: Build redocly HTML file
on: 
  push : 
    branches: [main]
    paths : 外部設計/API定義/OpenAPI.yml
  workflow_dispatch: # 手動実行用の設定項目
permissions:
  contents: write
jobs:
  run-redocly-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 外部設計/API定義/OpenAPI.yml
          sparse-checkout-cone-mode: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npx -y @redocly/cli build-docs 外部設計/API定義/OpenAPI.yml -o docs/redocly-openAPI.html
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add --sparse docs/redocly-openAPI.html
          git commit -m 'Auto-generate Redoc HTML from OpenAPI spec'

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
