name: spectral

on:
  push:
    branches:
      - docs
  pull_request: ~

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: npm install
        run: npm install 
      - uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: Install spectral
        run: npm ci

      - name: Lint
        run: npm run lint:ci
